#               ..----.._    _
#             .' .--.    "-.(O)_
# '-.__.-'"'=:|  ,  _)_ \__ . c\'-..
#             ''------'---''---'-"
#             Despelette was here !
# ---------------------------------------------

# Define System properties. You can add any property you want.
# properties:
#   property1: value1